# Generated by Django 3.1.7 on 2021-03-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_process', '0002_auto_20210326_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='output',
            field=models.ImageField(default='output/blue.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='photo',
            field=models.ImageField(default='output/blue.png', upload_to='documents'),
        ),
    ]
